### PR TITLE
feat: add deploy check in workflow

### PR DESCRIPTION
**Pull request by Mengchenchen**
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x893675** [comment]
@Mengchenchen  workflow can't run. i think you can fully tested before PR.

**Review by wu-wenxiang — CHANGES_REQUESTED** [review]
1. 需要先对 PR 打出临时包
2. 不要用 oss 上的 kcctl.sh，而应该用 PR 里的 kcctl.sh 脚本
3. kcctl.sh 应该支持用临时包部署
4. 用临时包安装好 kc
5. 用临时包安装 cluster

**Comment by x893675** [comment]
duplicate with #333 
/close

**Pull request closed without merging**
