### PR TITLE
fix: opa cve vuln

### PR DESCRIPTION
**Pull request by fengshunli**
### Which issue(s) this PR fixes:

Fixes #

### Special notes for reviewers:
```
```

### Does this PR introduced a user-facing change?

```release-note

```

### Additional documentation, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by x893675** [comment]
fix: #600

**Comment by x893675** [comment]
@fengshunli  Thanks for your contribution.  
Can you fix the build error

**Comment by fengshunli** [comment]
> @fengshunli Thanks for your contribution. Can you fix the build error

image
This field was annotated in version 1.26. What attribute should be used to print here? Can name be used?  @x893675 
image

**Comment by fengshunli** [comment]
@x893675 done

**Comment by x893675** [comment]
> > @fengshunli Thanks for your contribution. Can you fix the build error
> 
> image This field was annotated in version 1.26. What attribute should be used to print here? Can name be used? @x893675 image

I don't think this field is needed. @zhuzhenfan help reconfirm

**Comment by zhuzhenfan** [comment]
> > @fengshunli感谢您的贡献。你能修复构建错误吗
> 
> 图像 该字段在 1.26 版本中有注释。这里应该使用什么属性来打印？可以用名字吗？ @x893675 图像

Hi @fengshunli 
Thank you for your suggestion, we also found that clustername has been removed from the source code of k8s 1.26+. We will fix this bug after testing

**Comment by x893675** [comment]
kc-crash

@fengshunli  test in my local vm, server panic.

**Comment by fengshunli** [comment]
> kc-crash
> 
> @fengshunli test in my local vm, server panic.

@x893675 done

**Comment by lixd** [comment]
@fengshunli fixed, need rebase master and commit to recheck.

**Comment by fengshunli** [comment]
> @fengshunli fixed, need rebase master and commit to recheck.

@lixd see https://github.com/kubeclipper/kubeclipper/pull/625

**Pull request merged**
